package com.xvdereve.model;

public enum Country {
    France,
    Italie,
    Namibie,
    Nouvelle_Zélande,
    Uruguay,
    Afrique_du_Sud,
    Écosse,
    Irlande,
    Roumanie,
    Tonga,
    Australie,
    Fidji,
    Pays_de_Galles,
    Géorgie,
    Portugal,
    Argentine,
    Chili,
    Japon,
    Samoa,
    Angleterre,
    Russie,
    Canada,
    USA,
    Espagne,
    Cote_d_Ivoire,
    Zimbabwe,
}
