services:
  postgres:
    image: postgres:17
    container_name: xvdereve-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: xvdereve
      POSTGRES_USER: xvdereve
      POSTGRES_PASSWORD: xvdereve

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./xvdereve-back/database/init:/docker-entrypoint-initdb.d:ro
      - ./xvdereve-back/csv:/csv:ro

volumes:
  postgres_data: