spring.application.name=xvdereve-back

spring.datasource.url=jdbc:postgresql://localhost:5432/xvdereve
spring.datasource.username=xvdereve
spring.datasource.password=xvdereve

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false